### PR TITLE
Reference microsoft data sql client 5 0

### PR DESCRIPTION
**Pull request by alansingfield**
Reference to the issue I raised at:
https://github.com/dotMorten/Microsoft.SqlServer.Types/issues/78

Created new Debug_MSv4 and Release_MSv4 profiles; these reference Microsoft.Data.SqlClient 4.x.
Debug and Release profiles now reference Microsoft.Data.SqlClient 5.0 and give you a 3.5.x version number for the package.

I'm not sure what to do with the &lt;PackageValidationBaselineVersion&gt; section; since there is no 3.4 version. Can you advise?

### CODE REVIEW

**Comment by dotMorten** [comment]
I don't really see the point of this PR. You should be able to "override" the dependency by referencing a newer version explicitly in your app.

**Comment by alansingfield** [comment]
Because it fixes this bug:
https://github.com/dotMorten/Microsoft.SqlServer.Types/issues/78

When you upgrade to Microsoft.Data.SqlClient 5.0.1, interface IBinarySerialize is no longer within that library, so you get a TypeLoadException.

Microsoft have moved IBinarySerialize to a separate assembly in package Microsoft.SqlServer.Server 1.0.0. So the dotMorten.Microsoft.SqlServer.Types library needs to reference this package to work when using the newer Microsoft.Data.SqlClient.

**Comment by dotMorten** [comment]
@alansingfield In that case they made a binary breaking change, and should be addressed in that library, and the solution until then should be done with an assembly redirect. Adding a v3.0 just to reference a newer SDK isn't a road I want to continue down.
This library also has limited lifetime, now that they are finally working on adding proper xplat support to the official sqlclient types library.

**Comment by alansingfield** [comment]
OK got it - thanks for your advice.

I'll take a look at:
https://learn.microsoft.com/en-us/dotnet/standard/assembly/type-forwarding
https://learn.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support
https://learn.microsoft.com/en-us/dotnet/api/system.appdomain.typeresolve?view=net-6.0

**Pull request closed without merging**
